# Generated by Django 2.1.5 on 2020-01-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200122_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'exam_grade']},
        ),
    ]
